### ISSUE TITLE
想问一下 Env 中 Token 是通过什么渠道申请的？

### ISSUE THREAD

**Issue by GenerQAQ** [OrphanZhao/barcode-service#1]
感谢开源～想问一下 Env 中 Token 是通过什么渠道申请的？十分感谢！

**Comment by OrphanZhao** [comment]
这个是获取商品条码平台的数据平台对爬取数据有很多限制token是你登录那个平台以后去浏览器里看下就能找到

**Comment by GenerQAQ** [comment]
> 这个是获取商品条码平台的数据平台对爬取数据有很多限制token是你登录那个平台以后去浏览器里看下就能找到

感谢(🙏ˊᗜˋ*)，这样查询稳定吗，有查询次数限制吗

**Comment by OrphanZhao** [comment]
用于业务不行的 被屏蔽的概率很大

**Comment by GenerQAQ** [comment]
好滴 感谢回复！
